#!/usr/bin/env bash
# shellcheck shell=bash

# This file runs when a DM logs you into a graphical session.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/path.env" ]; then
    # shellcheck source=/dev/null
	. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/path.env"
fi

setbg &			# set desktop wallpaper
remaps &		# remaps keys and sets key autorepeat
numlockx    # toggle Numlock on
# redshift &  # adjusts the color temperature of your screen according to surroundings
autolock &  # sets a screensaver and locks the system when it timesout
xbanish &   # hide mouse cursor when using keyboard
dunst &			# dunst for notifications

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
