#!/usr/bin/env bash
# shellcheck shell=bash

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
  # shellcheck source=/dev/null
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
  # shellcheck source=/dev/null
	. "$HOME/.xprofile"
fi

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec i3 -V -d all &>> "${XDG_CACHE_HOME:="$HOME/.cache"}/i3.log"
fi
