#!/usr/bin/env bash
# shellcheck shell=bash

# This file runs when a DM logs you into a graphical session.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/path.env" ]; then
    # shellcheck source=/dev/null
	. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/path.env"
fi

# Load resource file
# Prefer Xresources > Xdefaults, as it is loaded into the RESOURCE_MANAGER property of the X11 root window.
# Source: <https://superuser.com/questions/243914/what-is-the-difference-between-xresources-and-xdefaults>

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" ]; then
   xrdb -merge -I"$XDG_CONFIG_HOME/x11" "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
elif [ -f "$HOME/.Xresources" ]; then
   xrdb -merge -I"$HOME" "$HOME/.Xresources"
elif [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xdefaults" ]; then
   xrdb -merge -I"$XDG_CONFIG_HOME/x11" "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xdefaults"
elif [ -f "$HOME/.Xdefaults" ]; then
   xrdb -merge -I"$HOME" "$HOME/.Xdefaults"
fi

xrandr@archbtw &	# setup multi-head displays
setbg &		      	# set desktop wallpaper
remaps &	      	# remaps keys and sets key autorepeat
numlockx          # toggle Numlock on
# redshift &      # adjusts the color temperature of your screen according to surroundings
autolock &        # sets a screensaver and locks the system when it timesout
xbanish &         # hide mouse cursor when using keyboard
dunst &			      # dunst for notifications

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
