#!/usr/bin/env bash
# shellcheck shell=bash

# This file is used for setting user's environment variables; it should not contain commands that produce output or assume the shell is attached to a TTY. When this file exists it will always be read.
# Source: <https://wiki.archlinux.org/title/Zsh>

# See: <https://www.reddit.com/r/zsh/comments/luoicb/zshenv_doesnt_export_variables_and_has_a_weird/>
export ZDOTDIR="${XDG_CONFIG_HOME:="$HOME/.config"}/zsh"
